# Generated by Django 4.1.2 on 2023-04-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Para",
            fields=[
                (
                    "Id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("date", models.IntegerField()),
                ("period", models.IntegerField()),
                ("nameC", models.CharField(max_length=500)),
                ("categ", models.CharField(max_length=100)),
                ("nameT", models.CharField(max_length=50)),
                ("place", models.CharField(max_length=500)),
            ],
        ),
    ]
