# Generated by Django 4.1.2 on 2023-04-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="para",
            name="nameT",
            field=models.CharField(max_length=30),
        ),
    ]
