# Generated by Django 4.1.2 on 2023-04-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_para_namet"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "Id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("nameT", models.CharField(max_length=30)),
            ],
        ),
    ]
